### PR TITLE
Fix copy/delete bug for contours

### LINKED ISSUE #21: Right click mouse menu often does not allow to copy
@carol-ux commented on [Thu May 13 2021](https://github.com/altis-labs/nota/issues/1128)

**Describe the bug**
On a regular basis, I do not get the option s"Copy" and "Delete" when I right click on a contour I want to copy. I try at different points but it keeps showing me only the "Paste" option. Even if I click on paste, often no contour appears or one appears and I delete the pasted contour and try to copy again, it does not work. You can try to zoom further in to see the individual contour dots and when you right click on one of those, you get the "Copy" menu.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a contour you want to copy
2. Right click on the contour
3. Only the "paste" option appears

**Expected behaviour**
When I right click on a contour, the correct option appears ( either the copy menu or paste). 

https://user-images.githubusercontent.com/71710321/118162761-20931d80-b3ef-11eb-8047-45fb332841ed.mov

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser Chrome

**Additional context**

---

@carol-ux commented on [Mon May 17 2021](https://github.com/altis-labs/nota/issues/1128#issuecomment-842628357)

https://user-images.githubusercontent.com/71710321/118554528-8e14b600-b72f-11eb-9782-8f92ab5695ab.mov

I right-clicked on the contour in each of the slices. Sometimes I just got the paste menu, sometimes not a menu at all. Even after I pasted, I still did not get the copy/delete menu.

### PR DESCRIPTION
**Pull request by d-projects**
Closes #21 

- The issue was that right clicking a contour at a part that was shared by another contour would not display the copy/delete options
- This issue was fixed by rearranging an array of 9 elements (containing handle data) so that the elements corresponding to the active contour were placed at the beginning

### CODE REVIEW

File: src/version.js [hunk 1]
```diff
@@ -1 +1 @@
-export default '1.1.9';
\ No newline at end of file
+export default '1.1.10';
```
Comment (mkramers) [inline src/version.js]: The next version should be `1.1.11` (see [here](https://github.com/altis-labs/cornerstoneTools/packages/564551)) - not sure why it was behind in the src

File: src/eventDispatchers/mouseEventHandlers/mouseDown.js [hunk 2]
```diff
@@ -88,7 +88,22 @@ export default function(evt) {
 
   if (annotationToolsWithMoveableHandles.length > 0) {
     const firstToolWithMoveableHandles = annotationToolsWithMoveableHandles[0];
-    const toolState = getToolState(element, firstToolWithMoveableHandles.name);
+    let toolState = getToolState(element, firstToolWithMoveableHandles.name);
+
+    // create a deep copy of toolState to avoid bad renders of contours after right clicks
+    toolState = JSON.parse(JSON.stringify(toolState));
+
+    const activeRoiId = firstToolWithMoveableHandles.roi.id;
```
Comment (mkramers) [inline src/eventDispatchers/mouseEventHandlers/mouseDown.js]: It's possible that `roi` will be `undefined`, so be sure to handle this case (i.e. only do the new logic when its not null)

File: src/eventDispatchers/mouseEventHandlers/mouseDown.js [hunk 3]
```diff
@@ -88,7 +88,22 @@ export default function(evt) {
...
+    let temporaryValue;
+
+    // Moves the elements with a roi id equal to the activeRoiId to the beginning of the toolState array
+    for (let i = 0; i < toolState.data.length; i++) {
+      if (toolState.data[i].roi.id === activeRoiId) {
+        temporaryValue = toolState.data[i];
+        toolState.data.splice(i, 1);
```
Comment (mkramers) [inline src/eventDispatchers/mouseEventHandlers/mouseDown.js]: NP: there is probably a more concise way of doing this without the `temporaryValue` (something like: https://stackoverflow.com/a/45516114/1620721) but this is ok for now

File: src/eventDispatchers/mouseEventHandlers/mouseDown.js [hunk 4]
```diff
@@ -88,7 +88,22 @@ export default function(evt) {
...
+
+    // create a deep copy of toolState to avoid bad renders of contours after right clicks
+    toolState = JSON.parse(JSON.stringify(toolState));
+
+    const activeRoiId = firstToolWithMoveableHandles.roi.id;
+    let temporaryValue;
+
+    // Moves the elements with a roi id equal to the activeRoiId to the beginning of the toolState array
+    for (let i = 0; i < toolState.data.length; i++) {
+      if (toolState.data[i].roi.id === activeRoiId) {
```
Comment (mkramers) [inline src/eventDispatchers/mouseEventHandlers/mouseDown.js]: It seems that changing this order causes existing contours to not be able to be deleted in `nota`:

```
Uncaught TypeError: Cannot destructure property 'wadoUrl' of 'instancesById[affectedInstanceId]' as it is undefined.
    at :3000/app/static/js/main.chunk.js:41757
    at :3000/app/static/js/0.chunk.js:553650
    at :3000/app/static/js/0.chunk.js:284317
    at deleteContourToolData (:3000/app/static/js/main.chunk.js:52596)
    at onContourDeleteClicked (:3000/app/static/js/main.chunk.js:52157)
    at HTMLUnknownElement.callCallback (:3000/app/static/js/0.chunk.js:513136)
    at Object.invokeGuardedCallbackDev (:3000/app/static/js/0.chunk.js:513185)
    at invokeGuardedCallback (:3000/app/static/js/0.chunk.js:513245)
    at invokeGuardedCallbackAndCatchFirstError (:3000/app/static/js/0.chunk.js:513260)
    at executeDispatch (:3000/app/static/js/0.chunk.js:517495)
    at processDispatchQueueItemsInOrder (:3000/app/static/js/0.chunk.js:517527)
    at processDispatchQueue (:3000/app/static/js/0.chunk.js:517540)
    at dispatchEventsForPlugins (:3000/app/static/js/0.chunk.js:517551)
    at :3000/app/static/js/0.chunk.js:517762
    at batchedEventUpdates$1 (:3000/app/static/js/0.chunk.js:531447)
    at batchedEventUpdates (:3000/app/static/js/0.chunk.js:512934)
    at dispatchEventForPluginEventSystem (:3000/app/static/js/0.chunk.js:517761)
    at attemptToDispatchEvent (:3000/app/static/js/0.chunk.js:515244)
    at dispatchEvent (:3000/app/static/js/0.chunk.js:515162)
    at unstable_runWithPriority (:3000/app/static/js/0.chunk.js:555577)
    at runWithPriority$1 (:3000/app/static/js/0.chunk.js:520542)
    at discreteUpdates$1 (:3000/app/static/js/0.chunk.js:531464)
    at discreteUpdates (:3000/app/static/js/0.chunk.js:512946)
    at dispatchDiscreteEvent (:3000/app/static/js/0.chunk.js:515128)
```

**Review by mkramers — CHANGES_REQUESTED** [review]

File: src/eventDispatchers/mouseEventHandlers/mouseDown.js (hunk 4 above)
Comment (d-projects) [reply src/eventDispatchers/mouseEventHandlers/mouseDown.js]: Completely forgot to test "Delete."

File: src/version.js (hunk 1 above)
Comment (d-projects) [reply src/version.js]: Fixed: 5de261c743432bd2a8b319b3e29f807eeb3537eb

File: src/eventDispatchers/mouseEventHandlers/mouseDown.js (hunk 2 above)
Comment (d-projects) [reply src/eventDispatchers/mouseEventHandlers/mouseDown.js]: Fixed: 5de261c743432bd2a8b319b3e29f807eeb3537eb

File: src/eventDispatchers/mouseEventHandlers/mouseDown.js (hunk 3 above)
Comment (d-projects) [reply src/eventDispatchers/mouseEventHandlers/mouseDown.js]: Tried something like this and it didn't work at first. I didn't want to waste another hour on it, so I just left it as is.

File: src/eventDispatchers/mouseEventHandlers/mouseDown.js (hunk 4 above)
Comment (d-projects) [reply src/eventDispatchers/mouseEventHandlers/mouseDown.js]: Making the deep copy caused the error, so I removed that. Maybe it might be better to "set" the toolState instead of having the state changed by reference... should I do that or leave it as is?

Commit: 5de261c743432bd2a8b319b3e29f807eeb3537eb

**Review by mkramers — APPROVED** [review]
